// <auto-generated />
namespace MapHive.Server.DataModel.DAL.Migrations.MetadataConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmailTemplateLocalisationModelChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailTemplateLocalisationModelChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201607071317218_EmailTemplateLocalisationModelChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
