// <auto-generated />
namespace MapHive.Server.Core.DAL.Migrations.MapHiveMetaConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class orgIdentifierAddedToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orgIdentifierAddedToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201702121531145_orgIdentifierAddedToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
